---
galaxy_info:
  role_name: post_install
  author: timilehin
  description: Install and configure Docker on Ubuntu servers
  company: ""

  license: MIT

  min_ansible_version: "2.15"

  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble

  galaxy_tags:
    - docker
    - containers
    - ubuntu
    - devops

dependencies: []